name: simpeg-benchmarks-mag
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - verde
  - tqdm
  - time
  # Jupyter
  - jupyter
  - jupytext
  # SimPEG's optional dependencies
  - dask
  - choclo
  # SimPEG requirements
  - numpy>=1.21
  - scipy>=1.8
  - pymatsolver>=0.2
  - matplotlib
  - discretize>=0.10
  - geoana>=0.5.0
  - empymod>=2.0.0
  - pip:
    - git+https://github.com/simpeg/simpeg.git@88e62352b023f5f2574ffc8f19e9a5c249f15f12
